import React, { Component } from 'react';
import Navbar from '../modules/Navbar';
import Footer from '../modules/Footer';
import { LeadSpace } from '@carbon/ibmdotcom-react';
// import { Accordion, AccordionItem } from 'carbon-components-react';
// import parse from 'html-react-parser';

class EmployersTerms extends Component {

  constructor(props) {
    super(props);
    this.state = JSON.parse(this.props.json);
  }

  render() {
    return (
      <>
        <Navbar />

        <div className="th--faq-leadpsace">
          <LeadSpace 
            theme="white"
            title={this.state.employers_terms.leadspace.title}
            copy={this.state.employers_terms.leadspace.subtitle}
            gradient={false}
            image={{
              sources: [
                { src: this.state.employers_terms.leadspace.background_image.small, breakpoint: 'sm' },
                { src: this.state.employers_terms.leadspace.background_image.medium, breakpoint: 'md' },
              ],
              defaultSrc: this.state.employers_terms.leadspace.background_image.large,
              alt: 'leadspace image',
            }}
          />
        </div>

        <div className="th--terms">
          <div className="bx--row">
            <div className="bx--col-lg-3"></div>
            <div className="bx--col-lg-10">
              <p><b>Employers at a glance:</b></p>
              <ul>
                <li>Registration is free for employers</li>
                <li>There is no charge for access to the TalentZoom platform - if Employer makes a hire through the TalentZoom platform, the success fee is equal to (1% of the hire’s compensation per month for up to 12 months).</li>
                <li>TalentZoom offers a full refund if the new hire is terminated or resigns within their first 60 days of employment</li>
                <li>Employers must notify TalentZoom if their Job Offer is accepted by a Job Seeker.</li>
              </ul>
              <p>TalentZoom, Inc. (“<b>TalentZoom</b>”, “<b>we</b>”, “<b>us</b>”, or “<b>our</b>”) invites you, the Employer (which term, as used herein, includes the company or organization (the “<b>Employer</b>”) on whose behalf we will provide services and in connection with the services Employer may be allowed to use our web site (collectively, the “<b>Services</b>”) which Employer can access at www.talentzoom.io (the “<b>Site</b>”). Please read these Employer Terms of Service (“<b>Terms of Service</b>”) carefully. By logging in and accessing the Site and by accepting our performance of Services, Employer acknowledges that Employer has read, understood, and agrees to be legally bound by these Terms of Service and to the collection and use of Employer information as set forth in our Privacy Policy. </p>
              <p>These Terms of Service may be updated by us from time to time with or without notice to Employer, and so Employer should review this page periodically. When material changes are made to these Terms of Service, we will update the “<b>Last Updated</b>” date at the top of this document, and notify Employer that material changes have been made. Employer’s continued use of the Site and/or Services constitutes Employer’s acceptance of such change(s). EMPLOYER AGREES TO REGULARLY CHECK THE SITE TO VIEW THE THEN-CURRENT TERMS OF SERVICE.</p>
              <p><b>1. DESCRIPTION OF OUR SERVICES.</b> TalentZoom is an online recruiting marketplace. Our Services allow Employers to connect with individuals seeking employment opportunities (each, a “<b>Job Seeker</b>”). We serve as intermediary between Job Seekers and Employers. TalentZoom is not involved in any contract of employment and is not bound by any contractual agreement arising between Job Seekers and employers, whether or not TalentZoom receives some form of remuneration in connection with the transaction.  Upon registering as an employer, Employer will be assigned a TalentZoom contact who will be responsible for the day-to-day management of Employer’s account (“<b>Account Partner</b>”). Employers will be able to view the collection of candidate profiles on www.talentzoom.io/jobseekers. If Employer would like to obtain additional information about a specific Job Seeker, Employer can do so by contacting your Account Partner. If Employer is interested in initiating a contact with a particular Job Seeker, Employer will be able to initiate the contact through the use of our Services by sending an interview request to the Job Seeker through the Services (each, an “<b>Interview Request</b>”) or through the Account Partner. Employer’s interaction with a Job Seeker may result in an offer for employment (“<b>Job Offer</b>”). Job Seekers may, in their sole discretion, accept or reject an Interview Request and/or a Job Offer.</p>
              <p><b>2. RIGHTS TO THE SERVICES.</b> Subject to the terms and conditions of these Terms of Service, Employer’s use of the Site shall be considered to be a non-exclusive, limited, non-transferable, freely revocable right to use the Site and the Services only and as permitted by the features of the Services. TalentZoom reserves all rights not expressly granted herein in the Services and the TalentZoom Content (as defined below). TalentZoom may terminate these provisions or rights at any time for any reason or no reason.</p>
              <p><b>3. CHANGES TO THE SERVICES.</b> We may, without prior notice, make changes, correction or improvements to the Services; stop providing the Services or features of the Services, to Employer or to users generally; or create usage limits for the Services. We may permanently or temporarily terminate or suspend Employer’s access to the Services without notice and liability for any reason, including if in our sole determination Employer violates any provision of these Terms of Service, or for no reason. Upon termination for any reason or no reason, Employer continues to be bound by these Terms of Service.</p>
              <p><b>4. REGISTRATION.</b> In order to access and use the Services, Employer must activate an Employer account. Employer may never use another user’s account without permission. During the onboarding process, Employer will have to provide Employer’s name, email address, and company name, and Employer will be asked to create a password for Employer’s account. Employer represents and warrants that all registration information Employer submits to us is truthful, complete and accurate, and Employer will maintain the accuracy of such information. Employer is solely responsible for the confidentiality of Employer’s account and for the activity that occurs on the account, and Employer must keep Employer’s account password secure. We encourage Employer to use “strong” passwords (passwords that use a combination of upper and lower case letters, numbers and symbols) for Employer’s account. Employer will promptly inform us of any need to deactivate Employer’s account. We reserve the right to delete or change Employer’s account at any time and for any reason. We are under no obligation to accept any individual or entity as an Employer, and may accept or reject any registration in our sole and complete discretion. Employer must notify us immediately of any breach of security or unauthorized use of Employer’s account. TalentZoom will not be liable for any losses caused by any unauthorized use of Employer’s account.</p>
              <p>Employer may control Employer’s account and how Employer interacts with the Services by changing the settings. By providing TalentZoom Employer’s email address Employer consents to our using the email address to send Employer Services-related notices, including any notices required by law, in lieu of communication by postal mail. We may also use Employer’s email address to send Employer other messages, such as changes to features of the Services and special offers. If Employer does not want to receive such email messages, Employer may opt out or change Employer’s preferences in Employer’s settings.  Opting out may prevent Employer from receiving email messages regarding updates, improvements, or offers.</p>
              <p><b>5. FEES.</b> Employer agrees to pay all applicable fees that are set forth on www.talentzoom.io/fees (“<b>Fees</b>”). Employer also agrees that any assignee or successor of Employer’s contractual obligations by virtue of a sale, exit or change of control transaction will also be obligated to pay any success fees for Job Seekers that Employer discovers through the Services.</p>
              <p><b>7. USE OF PERSONAL DATA.</b> Employer’s use of Services may involve the transmission to us of certain personally-identifiable information. Employer understands that by using the Services Employer consents to the collection, use and disclosure of Employer’s personally identifiable information as set forth in our Privacy Policy, and to have Employer’s personally identifiable information collected, used, transferred to and processed in the United States.</p>
              <p><b>8. COMMUNITY GUIDELINES.</b> TalentZoom’s community, like any community, functions best when its people follow a few simple rules. By accessing and/or using the Site and/or Services, Employer hereby agrees that:</p>
              <ul>
                <li>Employer will not use the Site and the Services for any unlawful purpose or to engage in any commercial activities, including, without limitation, raising money; advertising or promoting a product, service, or company; or engaging in any pyramid or other multi-tiered marketing scheme;</li>
                <li>Employer will not access or use the Site and the Services to collect any market research for a competing businesses;</li>
                <li>Employer will not upload, post, e-mail, transmit, or otherwise make available any content that:</li>
                <ul>
                  <li>infringes any copyright, trademark, right of publicity, or other proprietary rights of any person or entity; or</li>
                  <li>is threatening, tortious, defamatory, libelous, indecent, obscene, pornographic, sexually explicit, invasive of another’s privacy, or promotes extreme violence or cruelty to animals, or contains hate speech (i.e., speech that attacks or demeans a group based on race or ethnic origin, religion, disability, gender, age, veteran status, and/or sexual orientation/gender identity); or</li>
                  <li>discloses any sensitive information about another person, including that person’s e-mail address, postal address, phone number, credit card information, or any similar information.</li>
                </ul>
                <li>Employer will not “stalk” or otherwise harass another user of the Site and/or Services or any other person;</li>
                <li>Employer will not impersonate any person or entity or falsely state or otherwise misrepresent Employer’s affiliation with a person or entity;</li>
                <li>Employer agrees not to engage in any of the following prohibited activities:</li>
                <ul>
                  <li>copying, distributing, or disclosing any part of the Services in any medium, including without limitation by any automated or non-automated “scraping”;</li>
                  <li>using any automated system, including without limitation, “robots,” “spiders,” “offline readers,” etc., to access the Services in a manner that sends more request messages to TalentZoom’s servers than a human can reasonably produce in the same period of time by using a conventional on-line web browser (except that TalentZoom grants the operators of public search engines revocable permission to use spiders to copy publicly available materials from TalentZoom.io for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials);</li>
                  <li>transmitting spam, chain letters, or other unsolicited email;</li>
                  <li>attempting to interfere with, compromise the system integrity or security or decipher any transmissions to or from the servers running the Services;</li>
                  <li>taking any action that imposes, or may impose at our sole discretion an unreasonable or disproportionately large load on our infrastructure;</li>
                  <li>uploading invalid data, viruses, worms, or other software agents through the Services;</li>
                  <li>collecting or harvesting any personally identifiable information, including account names, from the Services;</li>
                  <li>using the Services for any commercial solicitation purposes;</li>
                  <li>impersonating another person or otherwise misrepresenting Employer’s affiliation with a person or entity, conducting fraud, hiding or attempting to hide Employer’s identity;</li>
                  <li>interfering with the proper working of the Services;</li>
                  <li>accessing any content on the Services through any technology or means other than those provided or authorized by the Services;</li>
                  <li>create multiple accounts for Employer for any reason, including, without limitation, in order to obtain the same promotion multiple times; or</li>
                  <li>bypassing the measures we may use to prevent or restrict access to the Services, including without limitation features that prevent or restrict use or copying of any content or enforce limitations on use of the Services or the content therein.</li>
                </ul>
                <li>We reserve the right, in our sole and absolute discretion, to deny Employer (or any device) access to the Site and/or the Services, or any portion of the Site and/or the Services, without notice.</li>
              </ul>
              <p><b>9. TALENTZOOM CONTENT.</b> Except for the Employer Content, the Site and the Services and all materials contained therein, including, but not limited to software, text, graphics, copy, images, artwork, logos, trademarks, service marks, copyrights, sound recordings, audiovisual works, photographs, content belonging to other users, including, but not limited to, Job Seeker Content (as defined below) and all copyrightable or otherwise legally protectable elements of the Services, including, without limitation, the design, selection, sequence, look and feel, and arrangement of the Services (collectively referred to as the “<b>TalentZoom Content</b>”), and all intellectual property rights related thereto, are the exclusive property of TalentZoom and its licensors (including, but not limited to, other employers, Job Seekers and users who post content to the Services). Except as explicitly provided herein, nothing in these Terms of Service shall be deemed to create a license in or under any such intellectual property rights, and Employer agrees not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works from any TalentZoom Content, or otherwise use the TalentZoom Content in any way for any public or commercial purpose. Use of the TalentZoom Content for any purpose not expressly permitted by these Terms of Service is strictly prohibited.</p>
              <p>Notwithstanding anything set forth in these Terms of Service, Employer may (a) make a limited number of copies of Job Seeker Content, and (b) distribute such content solely internally to its employees, in each case, (a) and (b), solely to the extent necessary to promote Employer’s hiring of the Job Seekers to whom such Job Seeker Content belongs. Employer must retain all copyright and other proprietary notices contained in the original TalentZoom Content on any copy Employer make of the TalentZoom Content. The use or posting of the TalentZoom Content on any other website or in a networked computer environment for any purpose is expressly prohibited.</p>
              <p>If Employer violates any part of these Terms of Service, Employer’s permission to access and/or use the TalentZoom Content, any access to the Site and/or the Services automatically terminates and Employer must immediately destroy any copies Employer have made of the TalentZoom Content.</p>
              <p><b>10. EMPLOYER CONTENT.</b> As noted above, the Services provide employers the ability to post and upload content including but not limited to, job description, and selection criteria (collectively, the “<b>Employer Content</b>”). Employer expressly acknowledges and agrees that once Employer submits Employer’s Employer Content through the Services, it will be accessible by Job Seekers, and that there is no confidentiality or privacy with respect to such Employer Content, including, without limitation, any personally identifying information that Employer may make available through the Services. EMPLOYER, AND NOT TALENTZOOM, IS ENTIRELY RESPONSIBLE FOR ALL EMPLOYER CONTENT THAT EMPLOYER UPLOADS, POSTS, E-MAILS, OR OTHERWISE TRANSMITS VIA THE SERVICES.</p>
              <p>Except for the license provided in this Section, Employer retains all copyrights and other intellectual property rights in and to Employer’s own Employer Content. Employer does, however, hereby grant TalentZoom a non-exclusive, royalty-free, sublicensable, transferable, perpetual license to modify, compile, combine with other content, copy, record, synchronize, transmit, translate, format, distribute, publicly display, publicly perform, and otherwise use or exploit Employer Content as reasonably necessary to provide the Services to Employer under these Terms of Service.</p>
              <p>If Employer submits Employer Content to TalentZoom, each such submission constitutes a representation and warranty to TalentZoom that Employer owns or otherwise has the valid right, by contract or otherwise, to grant to TalentZoom the rights and licenses described in these Terms of Service, deliver to TalentZoom the Employer Content and TalentZoom may use the Employer Content as permitted herein without violating any applicable law, rule or regulation or infringing or misappropriating any intellectual property or moral rights of any person, and that such Employer Content does not contain any libelous, defamatory, or obscene material or content that violates our Community Guidelines.</p>
              <p><b>11. COMMUNICATIONS WITH US.</b> Although we encourage Employer to e-mail us, we do not want Employer to, and Employer should not, e-mail us any content that contains confidential information. Employer may choose to or we may invite Employer to submit comments or ideas about the Services, including without limitation about how to improve the Service or our products (collectively, the “<b>Ideas</b>”). By submitting any Idea, Employer agrees that Employer’s disclosure is gratuitous, unsolicited and without restriction and will not place TalentZoom under any fiduciary or other obligation, and that we are free to use the Idea without any additional compensation to Employer, and/or to disclose the Idea on a non-confidential basis or otherwise to anyone. Employer further acknowledges that, by acceptance of Employer’s submission, TalentZoom does not waive any rights to use similar or related ideas previously known to TalentZoom, or developed by its employees, or obtained from sources other than Employer.</p>
              <p><b>12. NO WARRANTIES.</b> NONE OF TALENTZOOM, ITS AFFILIATES, SUBSIDIARIES, OR ANY OF ITS OR THEIR OFFICERS, DIRECTORS, EMPLOYEES OR AGENTS (COLLECTIVELY THE “<b>TALENTZOOM PARTIES</b>”) ENDORSE ANY JOB SEEKER, EMPLOYER, ANY JOB SEEKER CONTENT OR ANY CONTENT MADE AVAILABLE BY ANY EMPLOYER THROUGH THE SERVICES. EMPLOYER ACKNOWLEDGES THAT THE SERVICES MERELY ASSIST EMPLOYERS IN IDENTIFYING JOB SEEKERS THAT THEY ARE LOOKING TO HIRE. NONE OF THE TALENTZOOM PARTIES IS A PARTY TO, OR HAS ANY RESPONSIBILITY OR LIABILITY WITH RESPECT TO, ANY TRANSACTION, COMMUNICATION OR INTERACTION BETWEEN JOB SEEKERS AND EMPLOYERS OR FOR ANY RESULTS CAUSED BY USING THE SERVICES, INCLUDING WITHOUT LIMITATION, ANY PERSONAL INJURY OR PROPERTY DAMAGE.</p>
              <p>THE SERVICES AND THE SITE ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. USE OF THE SERVICES, THE SITE AND THE TALENTZOOM CONTENT IS AT EMPLOYER’S OWN RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES, THE SITE AND THE TALENTZOOM CONTENT IS PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY EMPLOYER FROM TALENTZOOM OR THROUGH THE SERVICES WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN. WITHOUT LIMITING THE FOREGOING, NONE OF THE TALENTZOOM PARTIES WARRANT THAT THE TALENTZOOM CONTENT IS ACCURATE, RELIABLE OR CORRECT; THAT THE SITE OR SERVICES WILL MEET EMPLOYER’S REQUIREMENTS; THAT THE SITE OR SERVICES WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION, UNINTERRUPTED OR SECURE; THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR THAT THE SITE OR SERVICES ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ANY TALENTZOOM CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SITE AND/OR SERVICE IS DOWNLOADED AT EMPLOYER’S OWN RISK AND EMPLOYER WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO EMPLOYER’S COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA THAT RESULTS FROM SUCH DOWNLOAD OR EMPLOYER’S USE OF THE SITE OR THE SERVICES.</p>
              <p>THE LAW IN CERTAIN JURISDICTIONS DOES NOT ALLOW THE EXCLUSION AND LIMITATIONS OF CERTAIN IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO EMPLOYER UNDER CERTAIN CIRCUMSTANCES. THESE TERMS OF SERVICE GIVE EMPLOYER SPECIFIC LEGAL RIGHTS, AND EMPLOYER MAY ALSO HAVE OTHER RIGHTS WHICH VARY ACCORDING TO JURISDICTION. THE DISCLAIMERS AND EXCLUSIONS UNDER THESE TERMS OF SERVICE WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>
              <p><b>13. LIMITATION OF LIABILITY.</b> TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL ANY OF THE TALENTZOOM PARTIES BE LIABLE FOR ANY SPECIAL, INDIRECT, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES, INCLUDING WITHOUT LIMITATION, DAMAGES FOR LOST PROFITS, REVENUES, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO THESE TERMS OF SERVICE, EVEN IF SUCH TALENTZOOM PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES IN ADVANCE. UNDER NO CIRCUMSTANCES WILL TALENTZOOM BE RESPONSIBLE FOR ANY DAMAGE, LOSS OR INJURY RESULTING FROM HACKING, TAMPERING OR OTHER UNAUTHORIZED ACCESS OR USE OF THE SERVICES OR EMPLOYER’S EMPLOYER ACCOUNT OR THE INFORMATION CONTAINED THEREIN.</p>
              <p>IN NO EVENT SHALL THE TOTAL CUMULATIVE LIABILITY OF THE TALENTZOOM PARTIES FOR ANY AND ALL DIRECT DAMAGES ARISING OUT OF OR RELATING TO THESE TERMS OF SERVICE, EXCEED THE TOTAL FEES RECEIVED BY TALENTZOOM FROM EMPLOYER IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE DATE OF WHICH SUCH CLAIM ARISES.</p>
              <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO EMPLOYER UNDER CERTAIN CIRCUMSTANCES. THESE TERMS OF SERVICE GIVE EMPLOYER SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS WHICH VARY ACCORDING TO JURISDICTION. THE DISCLAIMERS, EXCLUSIONS, AND LIMITATIONS OF LIABILITY UNDER THESE TERMS OF SERVICE WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>
              <p>EMPLOYER AGREES THAT YOU WILL NOT BRING ANY CLAIM UNDER THESE TERMS OF SERVICE MORE THAN EIGHTEEN (18) MONTHS AFTER THE CAUSE OF ACTION ARISES.</p>
              <p><b>14. INDEMNIFICATION.</b></p>
              <ul>
                <li>Employer will defend, indemnify, and hold the TalentZoom Parties harmless from and against any and all losses, liabilities, damages, demands, claims (including taxes), costs, payments and expenses (including any and all reasonable legal fees, reasonable costs of investigation, discovery, litigation and settlement, interest and any judgments, fines and penalties) as incurred, arising out of or in connection with any third-party claims (a) arising from or relating to (i) a violation or alleged violation of any applicable laws; (ii) Employer’s use of the Site, the Services, and/or the TalentZoom Content in breach of these Terms of Service, or (iii) the Employer Content or use of the Employer Content by any of the TalentZoom Parties in accordance with these Terms of Service infringing or misappropriating any intellectual property rights of, including without limitation, any copyright, trademark, trade secret, patent, privacy or publicity rights; or (b) brought against any TalentZoom Party by a Job Seeker as a result of any of Employer’s negligence or misconduct or in relation to Employer Content.</li>
                <li>TalentZoom will indemnify, defend and hold Employer, Employer’s affiliates, subsidiaries or any of Employer’s or their officers, directors, employees or agents (collectively, the “Employer Parties”) from and against any and all losses, liabilities, damages, demands, claims (including taxes), costs, payments and expenses (including any and all reasonable legal fees, reasonable costs of investigation, discovery, litigation and settlement, interest and any judgments, fines and penalties) as incurred, to the extent arising directly out of third-party claims to the extent arising out of Employer’s use of the Services consistent with this Agreement infringing or misappropriating any intellectual property rights of, including without limitation, any copyright, trademark, trade secret, patent, privacy or publicity rights except to the extent (a) any such claim arises from Employer’s negligence, misconduct, or fraud; or (b) Employer is subject to an indemnification obligation hereunder. The foregoing indemnification obligations in this paragraph do not apply with respect to portions or components of the Services (i) not supplied by TalentZoom, (ii) combined with other products, processes or materials where the alleged infringement relates to such combination, (iii) where any of the Employer Parties continue allegedly infringing activity after being notified thereof or after being informed of modifications that would have avoided the alleged infringement, or (iv) where any of the Employer Parties’ use of the Service is not strictly in accordance with this Agreement.</li>
                <li>The party to be indemnified (“<b>Indemnified Party</b>”) will give the indemnifying party (“<b>Indemnifying Party</b>”) prompt notice of any claim described in the preceding paragraphs (as applicable) (but the failure to give such notice will not relieve the Indemnifying Party of any of its obligations hereunder (as applicable) except to the extent the Indemnifying Party is materially prejudiced thereby), will allow the Indemnifying Party control of the defense of any such claim made against it (so long as any settlement (a) does not, without the Indemnified Party’s prior written approval, (i) involve the admission of any wrongdoing by any of the Indemnified Parties, (ii) restrict any Indemnified Parties’ future actions, or (iii) require any Indemnified Party to take any action, including the payment of money, and (b) includes a full release of all of the Indemnified Parties), and will give the Indemnifying Party reasonable assistance, at the Indemnifying Party’s expense, requested by the Indemnifying Party in writing in connection therewith. Each applicable Indemnified Party will have the right to participate in the defense of any such claim at its own expense, and such participation by such Indemnified Party will not relieve the Indemnifying Party of its indemnification obligations under this Section 14.</li>
              </ul>
              <p><b>15. EXTERNAL SITES.</b> The Site and the Services may contain links to third-party websites (“<b>External Sites</b>”). These links are provided solely as a convenience to Employer and not as an endorsement by us of the content on such External Sites. The content of such External Sites is developed and provided by others. We are not responsible for the content of any linked External Sites and do not make any representations regarding the content or accuracy of materials on such External Sites. Employer should take precautions when downloading files from all websites to protect Employer’s computer from viruses and other destructive programs. If Employer decide to access linked External Sites, Employer does so at Employer’s own risk.</p>
              <p><b>16. ACTIVE RECRUITING PROCESS.</b> Employer hereby agrees that:</p>
              <ul>
                <li>No Recruiting Activity (as defined below) has been in place between Employer and any Job Seeker for ninety (90) days prior to the date on which Employer first interacts with such Job Seeker through our Services. For the purposes of these Terms of Service, “<b>Recruiting Activity</b>” means a continuous direct, back and forth communication between an Employer and a Job Seeker in an active recruiting or hiring context where a decision to put a Job Seeker on hold or a decision to reject such Job Seeker has not been made.</li>
                <li>Employer will promptly inform us if Employer’s Job Offer is accepted by a Job Seeker and also provide us with a copy of the written, accepted job offer.  If there is no written  job offer or contract or if other details are needed by TalentZoom in its sole discretion to verify compensation, then Employer must provide us the details of the engagement as requested by us, including but not limited to the scope of the role, remuneration and other terms of the engagement. This may include for example pay rate verification taken from Employer’s payroll system.</li>
                <li>Employer will promptly notify us if the Job Seeker’s employment does not commence or is terminated within ninety (60) days from the start date that Employer agree to with the Job Seeker.</li>
                <li>Employer will use any content including but not limited to, resume / CV and job preferences submitted by the Job Seeker (collectively, the “<b>Job Seeker Content</b>”) in accordance with Section 17 of these Terms of Service.</li>
                <li>Employer will not disclose the names and identities of any Job Seekers listed on the site outside of Employer’s recruiting or hiring department.</li>
                <li>Employer will take appropriate physical, technical and administrative measures to protect Job Seeker Content from loss, misuse, unauthorized access, disclosure, alteration or destruction.</li>
                <li>Employer will not attempt to circumvent our Services by independently attempting to communicate and hire any of the Job Seekers through alternative means after discovering such Job Seekers through our Services.</li>
              </ul>
              <p><b>17. DATA SECURITY OBLIGATIONS.</b> Employer will:</p>
              <ul>
                <li>maintain, monitor and enforce a comprehensive written data security program and only Process (as defined below) Job Seeker Content in compliance with these Terms of Service and all applicable laws, regulations, government standards, industry standards, and best practices pertaining to privacy, data Processing, data protection, data security, encryption, and confidentiality (collectively, “<b>Applicable Processing Laws</b>”). As used in these Terms of Service, “<b>Process</b>” means to obtain, have access to, organize, copy, alter, use, disclose, store, erase, destroy or any other form of processing.</li>
                <li>Employer will maintain, monitor and enforce a data loss prevention automated program designed to detect and block data transfers of Job Seeker Content, if such transfers do not comply with this these Terms of Service.</li>
                <li>Employer will use Employer’s data security program to maintain, monitor and enforce reasonable organizational, administrative, technical and physical safeguards to protect the security, integrity, confidentiality and availability of Job Seeker Content, including to protect against: (a) any and all anticipated threats or hazards, and (b) any and all accidental, unauthorized or unlawful Processing, loss, or other compromise of Job Seeker Content (each, a “<b>Security Incident</b>”). Employer will promptly remediate all Security Incidents. Employer agrees to provide prompt notice to TalentZoom in the event of a Security Incident.</li>
                <li>Employer will provide TalentZoom with prompt written notice of any material modification to the process, method or means by which Job Seeker Content is processed (including any geographic change).</li>
                <li>Except as expressly permitted in these Terms of Service, Employer will not remove or transfer any of the Job Seeker Content outside of the Site and/or Services.</li>
              </ul>
              <p><b>18. COPYRIGHT COMPLAINTS.</b> TalentZoom respects the intellectual property rights of others and attempts to comply with all relevant laws. We will review all claims of copyright infringement received and remove any Content or user submissions deemed to have been posted or distributed in violation of any such laws. Our designated agent under the Digital Millennium Copyright Act (the “<b>Act</b>”) and any other like legislation for the receipt of any Notification of Claimed Infringement which may be given under that Act is as follows</p>
              <p>TalentZoom LLC. <br/>Attn: Copyright Agent<br/>________________________________________________<br/>________________________________________________</p>
              <p>If Employer believe that Employer’s work has been copied on the Site and/or the Services in a way that constitutes copyright infringement, please provide our agent with notice in accordance with the requirements of the Act, including (a) a description of the copyrighted work that has been infringed and the specific location on the Site and/or the Services where such work is located; (b) a description of the location of the original or an authorized copy of the copyrighted work; (c) Employer’s address, telephone number and e-mail address; (d) a statement by Employer that Employer have a good faith belief that the disputed use is not authorized by the copyright owner, its agent or the law; (e) a statement by Employer, made under penalty of perjury, that the information in Employer’s notice is accurate and that Employer are the copyright owner or authorized to act on the copyright owner’s behalf; and (f) an electronic or physical signature of the owner of the copyright or the person authorized to act on behalf of the owner of the copyright interest.</p>
              <p><b>19. MISCELLANEOUS.</b></p>
              <ul>
                <li>These Terms of Service will inure to the benefit of our successors, assigns and any licensees, and sublicensees, if applicable. These Terms of Service, and any rights and licenses granted hereunder, may not be transferred or assigned by Employer, but may be assigned by TalentZoom without restriction. Any attempted transfer or assignment in violation hereof shall be null and void.</li>
                <li>Employer agrees that we are not responsible to Employer for anything that may be caused by reasons beyond our reasonable control including, but not limited to, acts of God, earthquakes, war, insurrection, riots, crime, labor shortages (including lawful and unlawful strikes), embargoes, postal disruption, communication disruption, or failure or shortage of infrastructure.</li>
                <li>These Terms of Service will be governed by and construed in accordance with internal laws of the State of New York, without regard to the conflicts of law principles thereof, and any action brought in relation to this Agreement will be brought in a Federal or State court in New York County, New York State. Each party waives any right to trial by jury with respect to any dispute, suit, action or proceeding arising out of or relating to this Agreement or otherwise relating to the relationship of the parties, whether in contract, tort or otherwise. The parties agree that the United Nations Convention on Contracts for the International Sale of Goods will not apply.</li>
                <li>No waiver of any term of these Terms of Service shall be deemed a further or continuing waiver of such term or any other term, and TalentZoom’s failure to assert any right or provision under these Terms of Service shall not constitute a waiver of such right or provision.</li>
                <li>These Terms of Service, together with any amendments and any additional agreements Employer may enter into with TalentZoom in connection with the Service, shall constitute the entire agreement between Employer and TalentZoom concerning the Service. If any provision of these Terms of Service are deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Service, which shall remain in full force and effect. Notwithstanding the foregoing or anything else in these Terms of Service, the terms of these Terms of Service that by their terms are perpetual or are otherwise intended to survive these Terms of Service will survive the termination or expiration of these Terms of Service.</li>
                <li>The section headings in these Terms of Service are provided merely for convenience and shall not be given any legal import.</li>
                <li>Please contact Employer’s Account Partner with any questions regarding these Terms of Service.</li>
              </ul>
            </div>
          </div>
        </div>

        <Footer />
      </>
    );
  }
}

export default EmployersTerms;
