import React, { Component } from 'react';
import Navbar from '../modules/Navbar';
import Footer from '../modules/Footer';
import { LeadSpace } from '@carbon/ibmdotcom-react';
// import { Accordion, AccordionItem } from 'carbon-components-react';
// import parse from 'html-react-parser';

class JobSeekersTerms extends Component {

  constructor(props) {
    super(props);
    this.state = JSON.parse(this.props.json);
  }

  render() {
    return (
      <>
        <Navbar />

        <div className="th--faq-leadpsace">
          <LeadSpace 
            theme="white"
            title={this.state.job_seekers_terms.leadspace.title}
            copy={this.state.job_seekers_terms.leadspace.subtitle}
            gradient={false}
            image={{
              sources: [
                { src: this.state.job_seekers_terms.leadspace.background_image.small, breakpoint: 'sm' },
                { src: this.state.job_seekers_terms.leadspace.background_image.medium, breakpoint: 'md' },
              ],
              defaultSrc: this.state.job_seekers_terms.leadspace.background_image.large,
              alt: 'leadspace image',
            }}
          />
        </div>

        <div className="th--terms">
          <div className="bx--row">
            <div className="bx--col-lg-3"></div>
            <div className="bx--col-lg-10">
              <p><b>Job Seekers at a glance:</b></p>
              <ul>
                <li>TalentZoom is free for candidates</li>
                <li>Job Seekers must notify TalentZoom if they accept a Job Offer</li>
              </ul>
              <p>If you are located in the United States or Canada, welcome!</p>
              <p>If you are located outside of the United States or Canada, please read and agree to the following Terms of Service.</p>
              <p>TalentZoom LLC (“<b>TalentZoom</b>”, “<b>we</b>”, “<b>us</b>”, or “<b>our</b>”) invites you to use our online services and software provided on or in connection with the services (collectively, the “<b>Services</b>”) which you can access through our website located at <a href="/">www.talentzoom.io</a> (the “<b>Site</b>”). Please read these Job Seeker Terms of Service (“<b>Terms of Service</b>”) carefully. By logging in and accessing the Services, you acknowledge that you have read, understood, and agree to be legally bound by these Terms of Service and to the collection and use of your information as set forth in our Privacy Policy.</p>
              <p>We provide visitors to our Site (“<b>Visitors</b>”) access to our Site and Job Seekers (as defined below) with access to the Services subject to the terms and conditions set forth in these Terms of Service. By browsing the public areas of the Site or by clicking “I AGREE”, you acknowledge that you have read, understand and agree to be legally bound by these Terms of Service. If you do not agree to any of these terms, then please do not use the Site and/or the Services.</p>
              <p>These Terms of Service may be updated by us from time to time with or without notice to you, and so you should review this page periodically. When material changes are made to these Terms of Service, we will update the “<b>Last Updated</b>” date at the top of this document, and notify you that material changes have been made. Your continued use of the Site and/or Services constitutes your acceptance of such change(s). YOU AGREE TO REGULARLY CHECK THE SITE TO VIEW THE THEN-CURRENT TERMS OF SERVICE.</p>
              <p>THESE TERMS OF SERVICE CONTAIN A MANDATORY INDIVIDUAL ARBITRATION AND A CLASS ACTION/JURY TRIAL WAIVER PROVISION THAT REQUIRES YOU TO RESOLVE ALL DISPUTES THROUGH BINDING INDIVIDUAL ARBITRATION. THIS MEANS THAT YOU WAIVE ANY RIGHT TO HAVE THOSE DISPUTES DECIDED BY A JUDGE OR JURY AND THAT YOU WAIVE YOUR RIGHT TO PARTICIPATE IN CLASS ACTIONS, CLASS ARBITRATIONS, OR REPRESENTATIVE ACTIONS.</p>
              <p><b>1. DESCRIPTION OF OUR SERVICES.</b> TalentZoom is an online recruiting marketplace. Our Services allow individuals seeking employment opportunities (each, a “<b>Job Seeker</b>”) to connect with companies seeking to recruit such individuals (each, an “<b>Employer</b>”). We serve as intermediary between Job Seekers and Employers. TalentZoom is not involved in any contract of employment and is not bound by any contractual agreement arising between Job Seekers and Employers, whether or not TalentZoom receives some form of remuneration in connection with the transaction. Upon registering as a Job Seeker, you may be matched with an Employer and receive a request to interview (“<b>Interview Request</b>”). When matched with an Employer, your Personal Information (as defined below) will be visible and accessible by Employers and the Employers can also ask for additional information about you.  You may, in your sole discretion, accept or reject an Interview Request. Your interaction with an Employer may result in the Employer extending an offer for employment to you (“<b>Job Offer</b>”). You may, in your sole discretion, accept or reject a Job Offer.</p>
              <p><b>2. ELIGIBILITY.</b> This is a contract between you and TalentZoom. You may use the Services only if you can form a binding contract with TalentZoom, and only in compliance with these Terms of Service and all applicable laws, rules and regulations. The Services are only available for individuals aged 18 years or older. If you are under 18 years of age, you are not permitted to use the Services. Any use or access to the Services by anyone under 13 is strictly prohibited and in violation of these Terms of Service. The Services are not available to any Visitors or Job Seekers previously removed from the Services by TalentZoom.</p>
              <p><b>3. RIGHTS TO THE SERVICES.</b> Subject to the terms and conditions of these Terms of Service, you are hereby granted a non-exclusive, limited, non-transferable, freely revocable right to use the Services only and as permitted by the features of the Services. TalentZoom reserves all rights not expressly granted herein in the Services and the TalentZoom Content (as defined below). TalentZoom may terminate this license at any time for any reason or no reason.</p>
              <p><b>4. CHANGES TO THE SERVICE.</b> TalentZoom may, without prior notice, make changes, corrections or improvements to the Services; stop providing the Services or features of the Services, to you or to users generally; or create usage limits for the Services. We may permanently or temporarily terminate or suspend your access to the Services without notice and liability for any reason, including if in our sole determination you violate any provision of these Terms of Service, or for no reason. Upon termination for any reason or no reason, you continue to be bound by these Terms of Service.</p>
              <p><b>5. REGISTRATION.</b> In order to access and use the Services, you must register by creating a Job Seeker account. You may never use another user’s account without permission. During the registration process, you will have to provide your name, email address, and phone number and you will be asked to create a password for your account. You represent and warrant that all registration information you submit to us is truthful, complete and accurate, and you will maintain the accuracy of such information. You are solely responsible for the confidentiality of your Job Seeker account and for the activity that occurs on the account, and you must keep your account password secure. We encourage you to use “strong” passwords (passwords that use a combination of upper and lower case letters, numbers and symbols) with your account. You will promptly inform us of any need to deactivate your Job Seeker account. We reserve the right to delete or change your Job Seeker account at any time and for any reason. We are under no obligation to accept any individual as a Job Seeker, and may accept or reject any registration in our sole and complete discretion. You must notify us immediately of any breach of security or unauthorized use of your Job Seeker account. TalentZoom will not be liable for any losses caused by any unauthorized use of your Job Seeker account.</p>
              <p>You may control your Job Seeker account and how you interact with the Services by changing the settings in your settings page. By providing TalentZoom your email address you consent to our using the email address to send you Services-related notices, including any notices required by law, in lieu of communication by postal mail. We may also use your email address to send you other messages, such as changes to features of the Services and special offers. If you do not want to receive such email messages, you may opt out or change your preferences in your settings page. Opting out may prevent you from receiving email messages regarding updates, improvements, or offers.</p>
              <p><b>6. FEES.</b> Services are currently provided to you for free.</p>
              <p><b>7. CONTRACTOR ENGAGEMENTS.</b> This Section 7 only applies to contractor engagements in the United States. In the case of a Job Seeker hired on a contractor basis (a “<b>Contractor Engagement</b>”) Alleanza Partners (“<b>Agency</b>”) will manage such Contractor Engagement. Agency operates as the employer of record for all Contractor Engagements. Agency shall be responsible for all Job Seeker contractor compensation, including, if applicable, payroll and payroll taxes, worker’s compensation, unemployment insurance, and health insurance. Employer will not pay Job Seeker contractor directly.</p>
              <p><b>8. USE OF PERSONAL DATA.</b> Your use of Services may involve the transmission to us of certain personally-identifiable information. You understand that by using the Services you consent to the collection, use and disclosure of your personally identifiable information as set forth in our Privacy Policy, and to have your personally identifiable information collected, used, transferred to and processed in the United States or Canada.</p>
              <p><b>9. COMMUNITY GUIDELINES.</b> TalentZoom’s community, like any community, functions best when its people follow a few simple rules. By accessing and/or using the Site and/or Services, you hereby agree that:</p>
              <p>
                <ul>
                  <li>You will not use the Site and the Services for any unlawful purpose or to engage in any commercial activities, including, without limitation, raising money; advertising or promoting a product, service, or company; or engaging in any pyramid or other multi-tiered marketing scheme;</li>
                  <li>You will not access or use the Site or the Services to collect any market research for a competing businesses;</li>
                  <li>You will not upload, post, e-mail, transmit, or otherwise make available any content that:</li>
                  <ul>
                    <li>infringes any copyright, trademark, right of publicity, or other proprietary rights of any person or entity; or</li>
                    <li>is threatening, tortious, defamatory, libelous, indecent, obscene, pornographic, sexually explicit, invasive of another’s privacy, or promotes extreme violence or cruelty to animals, or contains hate speech (i.e., speech that attacks or demeans a group based on race or ethnic origin, religion, disability, gender, age, veteran status, and/or sexual orientation/gender identity; or</li>
                    <li>discloses any sensitive information about another person, including that person’s e-mail address, postal address, phone number, credit card information, or any similar information.</li>
                  </ul>
                  <li>You will not “stalk” or otherwise harass another user of the Site and/or Services or any other person;</li>
                  <li>You will not impersonate any person or entity or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
                  <li>You agree not to engage in any of the following prohibited activities:</li>
                  <ul>
                    <li>copying, distributing, or disclosing any part of the Services in any medium, including without limitation by any automated or non-automated “scraping”;</li>
                    <li>using any automated system, including without limitation, “robots,” “spiders,” “offline readers,” etc., to access the Services in a manner that sends more request messages to TalentZoom’s servers than a human can reasonably produce in the same period of time by using a conventional on-line web browser (except that TalentZoom grants the operators of public search engines revocable permission to use spiders to copy publicly available materials from TalentZoom.io for the sole purpose of and solely to the extent necessary for creating publicly available searchable indexes of the materials, but not caches or archives of such materials);</li>
                    <li>transmitting spam, chain letters, or other unsolicited email;</li>
                    <li>attempting to interfere with, compromise the system integrity or security or decipher any transmissions to or from the servers running the Services;</li>
                    <li>taking any action that imposes, or may impose at our sole discretion an unreasonable or disproportionately large load on our infrastructure;</li>
                    <li>uploading invalid data, viruses, worms, or other software agents through the Services;</li>
                    <li>collecting or harvesting any personally identifiable information, including account names, from the Services;</li>
                    <li>using the Services for any commercial solicitation purposes;</li>
                    <li>impersonating another person or otherwise misrepresenting your affiliation with a person or entity, conducting fraud, hiding or attempting to hide your identity;</li>
                    <li>interfering with the proper working of the Services;</li>
                    <li>accessing any content on the Services through any technology or means other than those provided or authorized by the Services;</li>
                    <li>create multiple accounts for you for any reason, including, without limitation, in order to obtain the same promotion multiple times; or</li>
                    <li>bypassing the measures we may use to prevent or restrict access to the Services, including without limitation features that prevent or restrict use or copying of any content or enforce limitations on use of the Services or the content therein.</li>
                  </ul>
                </ul>
              </p>
              <p>We reserve the right, in our sole and absolute discretion, to deny you access to the Site and/or the Services, or any portion of the Site and/or the Services, without notice.</p>
              <p><b>10. JOB SEEKER CONTENT.</b> As noted above, the Services provide Job Seekers the ability to post and upload content including but not limited to, their resume / CV and job preferences (collectively, the “<b>Job Seeker Content</b>”). You expressly acknowledge and agree that once you submit your Job Seeker Content through the Services, it will be accessible by Employers, and that there is no confidentiality or privacy with respect to such Job Seeker Content, including, without limitation, any personally identifying information that you may make available through the Services. YOU, AND NOT TALENTZOOM, ARE ENTIRELY RESPONSIBLE FOR ALL YOUR JOB SEEKER CONTENT THAT YOU UPLOAD, POST, E-MAIL, OR OTHERWISE TRANSMIT VIA THE SERVICES.</p>
              <p>Except for the licenses in this Section, you retain all copyrights and other intellectual property rights in and to your own Job Seeker Content. You do, however, hereby grant us a non-exclusive, royalty-free, sublicensable, transferable, perpetual license to modify, compile, combine with other content, copy, record, synchronize, transmit, translate, format, distribute, publicly display, publicly perform, and otherwise use or exploit your Job Seeker Content as reasonably necessary to provide the Services to you under these Terms of Service.</p>
              <p><b>11. COMMUNICATIONS WITH US.</b> Although we encourage you to e-mail us, we do not want you to, and you should not, e-mail us any content that contains confidential information. You may choose to or we may invite you to submit comments or ideas about the Services, including without limitation about how to improve the Service or our products (collectively, the “<b>Ideas</b>”). By submitting any Idea, you agree that your disclosure is gratuitous, unsolicited and without restriction and will not place TalentZoom under any fiduciary or other obligation, and that we are free to use the Idea without any additional compensation to you, and/or to disclose the Idea on a non-confidential basis or otherwise to anyone. You further acknowledge that, by acceptance of your submission, TalentZoom does not waive any rights to use similar or related ideas previously known to TalentZoom, or developed by its employees, or obtained from sources other than you.</p>
              <p><b>12. NO WARRANTIES.</b> NONE OF TALENTZOOM, ITS AFFILIATES, SUBSIDIARIES, OR ANY OF ITS OR THEIR OFFICERS, DIRECTORS, EMPLOYEES OR AGENTS (COLLECTIVELY THE “<b>TALENTZOOM PARTIES</b>”) ENDORSE ANY JOB SEEKER, EMPLOYER, ANY JOB SEEKER CONTENT OR ANY CONTENT MADE AVAILABLE BY ANY EMPLOYER THROUGH THE SERVICES. YOU ACKNOWLEDGE THAT THE SERVICES MERELY ASSISTS JOB SEEKERS IN IDENTIFYING JOB OPPORTUNITIES THAT MEET THEIR REQUIREMENTS. NONE OF THE TALENTZOOM PARTIES IS A PARTY TO, OR HAS ANY RESPONSIBILITY OR LIABILITY WITH RESPECT TO, ANY TRANSACTION, COMMUNICATION OR INTERACTION BETWEEN JOB SEEKERS AND EMPLOYERS OR FOR ANY RESULTS CAUSED BY USING THE SERVICES, INCLUDING WITHOUT LIMITATION, ANY PERSONAL INJURY OR PROPERTY DAMAGE.</p>
              <p>THE SERVICES AND THE SITE ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. USE OF THE SERVICES, THE SITE AND THE TALENTZOOM CONTENT IS AT YOUR OWN RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES, THE SITE AND THE TALENTZOOM CONTENT IS PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM TALENTZOOM OR THROUGH THE SERVICES WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN. WITHOUT LIMITING THE FOREGOING, NONE OF THE TALENTZOOM PARTIES WARRANT THAT THE TALENTZOOM CONTENT IS ACCURATE, RELIABLE OR CORRECT; THAT THE SITE OR SERVICES WILL MEET YOUR REQUIREMENTS; THAT THE SITE OR SERVICES WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION, UNINTERRUPTED OR SECURE; THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR THAT THE SITE OR SERVICES ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ANY TALENTZOOM CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SITE AND/OR SERVICE IS DOWNLOADED AT YOUR OWN RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA THAT RESULTS FROM SUCH DOWNLOAD OR YOUR USE OF THE SITE OR THE SERVICES.</p>
              <p><b>13. LIMITATION OF LIABILITY.</b> TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL ANY OF THE TALENTZOOM PARTIES BE LIABLE FOR ANY: (I) INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOST PROFITS, REVENUES, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO THESE TERMS OF SERVICE, EVEN IF SUCH TALENTZOOM PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; AND (II) ANY DIRECT DAMAGES THAT YOU MAY SUFFER AS A RESULT OF YOUR USE OF THE SITE, THE SERVICES OR THE TALENTZOOM CONTENT SHALL BE LIMITED TO ONE HUNDRED DOLLARS ($100). UNDER NO CIRCUMSTANCES WILL TALENTZOOM BE RESPONSIBLE FOR ANY DAMAGE, LOSS OR INJURY RESULTING FROM HACKING, TAMPERING OR OTHER UNAUTHORIZED ACCESS OR USE OF THE SERVICES OR YOUR JOB SEEKER ACCOUNT OR THE INFORMATION CONTAINED THEREIN.</p>
              <p>IN NO EVENT SHALL THE TOTAL CUMULATIVE LIABILITY OF THE TALENTZOOM PARTIES FOR ANY AND ALL DIRECT DAMAGES ARISING OUT OF OR RELATING TO THESE TERMS OF SERVICE, EXCEED, THE TOTAL FEES RECEIVED BY TALENTZOOM FROM YOU IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE DATE OF WHICH SUCH CLAIM ARISES.</p>
              <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. THESE TERMS OF SERVICE GIVE YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS WHICH VARY ACCORDING TO JURISDICTION. THE DISCLAIMERS, EXCLUSIONS, AND LIMITATIONS OF LIABILITY UNDER THESE TERMS OF SERVICE WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>
              <p>YOU AGREE THAT YOU WILL NOT BRING ANY CLAIM UNDER THESE TERMS OF SERVICE MORE THAN EIGHTEEN (18) MONTHS AFTER THE CAUSE OF ACTION ARISES.</p>
              <p><b>14. INDEMNIFICATION.</b> You agree to defend, indemnify, and hold the TalentZoom Parties harmless from and against any and all losses, liabilities, damages, demands, claims (including taxes), costs, payments and expenses (including any and all reasonable attorneys’ fees, reasonable costs of investigation, discovery, litigation and settlement, interest and any judgments, fines and penalties) as incurred, arising out of or in connection with any third-party claims (a) arising from or relating to: (i) your violation of any term of these Terms of Service, including without limitation, your breach of any of the representations and warranties herein; (ii) your misuse of the Site, the Services, and/or the TalentZoom Content, (iii) your Job Seeker Content or any content that is submitted via your Job Seeker account, including without limitation, misleading, false, or inaccurate information, (iv) your violation of any third-party right, including without limitation, any copyright, trademark, trade secret, privacy or publicity right, (v) any other party’s access and/or use of the Services with your unique username, password or other appropriate security code, or (vi) a violation or alleged violation of any applicable laws; or (b) any claims brought against any TalentZoom Party by an Employer as a result of any of your gross negligence or willful misconduct.</p>
              <p><b>15. EXTERNAL SITES.</b> The Site and the Services may contain links to third-party websites (“<b>External Sites</b>”). These links are provided solely as a convenience to you and not as an endorsement by us of the content on such External Sites. The content of such External Sites is developed and provided by others. We are not responsible for the content of any linked External Sites and do not make any representations regarding the content or accuracy of materials on such External Sites. You should take precautions when downloading files from all websites to protect your computer from viruses and other destructive programs. If you decide to access linked External Sites, you do so at your own risk.</p>
              <p><b>16. ACTIVE RECRUITING PROCESS.</b> If you are a Job Seeker, you hereby agree that:</p>
              <ul>
                <li>No Recruiting Activity (as defined below) has been in place between you and any Employer for ninety (90) days prior to the date on which you first interact with such Employer through our Services. For the purposes of these Terms of Service, “<b>Recruiting Activity</b>” means a continuous direct, back and forth communication between an Employer and a Job Seeker in an active recruiting or hiring context where a decision to put a Job Seeker on hold or a decision to reject such Job Seeker has not been made.</li>
                <li>You will initiate any initial interaction with any Employer exclusively through the Services. Further communication may take place outside of our Services only after the Interview Request is sent out by the Employer and accepted by the Job Seeker.</li>
                <li>You will promptly inform us upon receipt of a Job Offer, including but not limited to, the details on the beginning of the employment, duration and compensation.</li>
                <li>You will promptly inform us if you accept a Job Offer and also provide us with a copy of the written Job Offer (and a signed version, if one is signed). If there is no written Job Offer or if other details are needed by TalentZoom in its sole discretion to verify compensation, then you must provide us the details of the engagement as requested by us, including but not limited to the scope of the role, remuneration and other terms of the engagement.</li>
                <li>You will not publicly or privately disclose, post or disseminate any Job Offers that you receive through the Services.</li>
                <li>You will not attempt to circumvent our Services by independently attempting to communicate with an Employer that contacted or communicated with you through our Services.</li>
              </ul>
              <p><b>17. COMPLIANCE WITH LAWS.</b> Whether inside or outside of the United States or Canada, you are solely responsible for ensuring compliance with the applicable laws of your specific jurisdiction.</p>
              <p><b>18. COPYRIGHT COMPLAINTS.</b> TalentZoom respects the intellectual property rights of others and attempts to comply with all relevant laws. We will review all claims of copyright infringement received and remove any Content or user submissions deemed to have been posted or distributed in violation of any such laws.</p>
              <p>Our designated agent under the Digital Millennium Copyright Act and any other like legislation (the “Act”) for the receipt of any Notification of Claimed Infringement which may be given under that Act is as follows: </p>
              <p>TalentZoom LLC. <br/>Attn: Copyright Agent<br/>________________________________________________<br/>________________________________________________</p>
              <p>If you believe that your work has been copied on the Site and/or the Services in a way that constitutes copyright infringement, please provide our agent with notice in accordance with the requirements of the Act, including (a) a description of the copyrighted work that has been infringed and the specific location on the Site and/or the Services where such work is located; (b) a description of the location of the original or an authorized copy of the copyrighted work; (c) your address, telephone number and e-mail address; (d) a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent or the law; (e) a statement by you, made under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf; and (f) an electronic or physical signature of the owner of the copyright or the person authorized to act on behalf of the owner of the copyright interest.</p>
              <p><b>19. GOVERNING LAW.</b> These Terms of Service shall be governed by the internal substantive laws of the State of New York, without respect to its conflict of laws principles.  You agree to submit to the personal jurisdiction of the federal and state courts located in New York County, New York State for any actions for which we retain the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of our copyrights, trademarks, trade secrets, patents, or other intellectual property or proprietary rights, as set forth in the Arbitration provision below, including any provisional relief required to prevent irreparable harm. You agree that New York County, New York State is the proper forum for any appeals of an arbitration award or for trial court proceedings in the event that the arbitration provision below is found to be unenforceable.</p>
              <p><b>20. ARBITRATION.</b> READ THIS SECTION CAREFULLY BECAUSE IT REQUIRES THE PARTIES TO ARBITRATE THEIR DISPUTES AND LIMITS THE MANNER IN WHICH YOU CAN SEEK RELIEF FROM TALENTZOOM. FOR ANY DISPUTE WITH TALENTZOOM, YOU AGREE TO FIRST CONTACT US AT INFO@TALENTZOOM.IO AND ATTEMPT TO RESOLVE THE DISPUTE WITH US INFORMALLY. IN THE UNLIKELY EVENT THAT TALENTZOOM HAS NOT BEEN ABLE TO RESOLVE A DISPUTE WITHIN SIXTY (60) DAYS OF YOUR FIRST CONTACT, YOU AND TALENTZOOM AGREE THAT THE SOLE AND EXCLUSIVE FORUM AND REMEDY FOR ANY AND ALL DISPUTES AND CLAIMS RELATING IN ANY WAY TO OR ARISING OUT OF THESE TERMS OF SERVICE SHALL BE FINAL AND BINDING ARBITRATION. THE FEDERAL ARBITRATION ACT AND FEDERAL ARBITRATION LAW APPLY TO THESE TERMS.</p>
              <p>THERE IS NO JUDGE OR JURY IN ARBITRATION, AND COURT REVIEW OF AN ARBITRATION AWARD IS LIMITED. HOWEVER, AN ARBITRATOR CAN AWARD ON AN INDIVIDUAL BASIS THE SAME DAMAGES AND RELIEF AS A COURT (INCLUDING INJUNCTIVE AND DECLARATORY RELIEF OR STATUTORY DAMAGES), AND MUST FOLLOW THE TERMS OF THESE TERMS OF SERVICE AS A COURT WOULD.</p>
              <p>ANY DISPUTE BETWEEN TALENTZOOM AND YOU ABOUT OR INVOLVING YOUR USE OF THE SERVICES THAT IS UNABLE TO BE INFORMALLY RESOLVED MUST BE COMMENCED AND CONDUCTED IN NEW YORK, NEW YORK, USA UNDER THE COMMERCIAL ARBITRATION RULES (THE “AAA RULES”) OF THE AMERICAN ARBITRATION ASSOCIATION (“AAA”) AND, WHERE APPROPRIATE, THE AAA’S SUPPLEMENTARY PROCEDURES FOR CONSUMER RELATED DISPUTES (“AAA CONSUMER RULES”), BOTH OF WHICH ARE AVAILABLE AT THE AAA WEBSITE WWW.ADR.ORG OR BY CALLING THE AAA AT 1-800-778-7879.  THE FOREGOING SHALL NOT PREVENT TALENTZOOM FROM SEEKING INJUNCTIVE RELIEF IN A COURT OF COMPETENT JURISDICTION. JUDGMENT ON THE AWARD MAY BE ENTERED IN ANY COURT OF COMPETENT JURISDICTION.</p>
              <p><b>21. CLASS ACTION/JURY TRIAL WAIVER.</b> WITH RESPECT TO ALL PERSONS AND ENTITIES, REGARDLESS OF WHETHER THEY HAVE OBTAINED OR USED THE SERVICES FOR PERSONAL, COMMERCIAL OR OTHER PURPOSES, TALENTZOOM AND USER EACH AGREE THAT TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, ANY DISPUTE RESOLUTION PROCEEDINGS WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED OR REPRESENTATIVE ACTION. </p>
              <p>IF FOR ANY REASON A CLAIM PROCEEDS IN COURT RATHER THAN IN ARBITRATION TALENTZOOM AND EACH USER HEREBY WAIVES ANY RIGHT TO A JURY TRIAL.</p>
              <p><b>22. MISCELLANEOUS</b></p>
              <ul>
                <li>These Terms of Service will inure to the benefit of our successors, assigns, licensees, and sublicensees. These Terms of Service, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by TalentZoom without restriction. Any attempted transfer or assignment in violation hereof shall be null and void.</li>
                <li>No waiver of any term of these Terms of Service shall be deemed a further or continuing waiver of such term or any other term, and TalentZoom’s failure to assert any right or provision under these Terms of Service shall not constitute a waiver of such right or provision.</li>
                <li>These Terms of Service, together with any amendments and any additional agreements you may enter into with TalentZoom in connection with the Service, shall constitute the entire agreement between you and TalentZoom concerning the Service. If any provision of these Terms of Service are deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Service, which shall remain in full force and effect. Notwithstanding the foregoing or anything else in these Terms of Service, the terms of these Terms of Service that by their terms are perpetual or are otherwise intended to survive these Terms of Service will survive the termination or expiration of these Terms of Service.</li>
                <li>The section headings in these Terms of Service are provided merely for convenience and shall not be given any legal import.</li>
                <li>Please contact us at info@talentzoom.io with any questions regarding these Terms of Service.</li>
              </ul>
            </div>
          </div>
        </div>

        <Footer />
      </>
    );
  }
}

export default JobSeekersTerms;
