import React, { Component } from 'react';
import Navbar from '../modules/Navbar';
import Footer from '../modules/Footer';
import { LeadSpace } from '@carbon/ibmdotcom-react';
// import { Accordion, AccordionItem } from 'carbon-components-react';
// import parse from 'html-react-parser';

class Privacy extends Component {

  constructor(props) {
    super(props);
    this.state = JSON.parse(this.props.json);
  }

  render() {
    return (
      <>
        <Navbar />

        <div className="th--faq-leadpsace">
          <LeadSpace 
            theme="white"
            title={this.state.privacy.leadspace.title}
            copy={this.state.privacy.leadspace.subtitle}
            gradient={false}
            image={{
              sources: [
                { src: this.state.privacy.leadspace.background_image.small, breakpoint: 'sm' },
                { src: this.state.privacy.leadspace.background_image.medium, breakpoint: 'md' },
              ],
              defaultSrc: this.state.privacy.leadspace.background_image.large,
              alt: 'leadspace image',
            }}
          />
        </div>

        <div className="th--terms">
          <div className="bx--row">
            <div className="bx--col-lg-3"></div>
            <div className="bx--col-lg-10">
              <p>TalentZoom (“<b>TalentZoom</b>”, “<b>we”</b>, “<b>us</b>”, or “<b>our</b>”) takes privacy issues very seriously and we are fully committed to ensuring security of information. This Privacy Policy explains how your personal information is collected, used and disclosed by TalentZoom. This Privacy Policy applies to our website, <a href="/">www.talentzoom.io</a> (our “<b>Site</b>”) and the services and software provided on or in connection with the Site (collectively, the “<b>Service</b>”). Please read this Privacy Policy carefully as it contains important information regarding data collection and use.</p>
              <p>Capitalized terms not defined in this Privacy Policy shall have the meaning set forth in the Terms of Service for Job Seekers and for Employers, respectively.</p>
              <p><b>1. DEFINITIONS</b></p>
              <ol>
                <li>"<b>Personal Information</b>" means any data collected from you that may allow yourself to be identified. This may include, without limitation, your name, phone number, e-mail address, physical address and any other identifying information.</li>
                <li>"<b>Non-Personal Information</b>" shall refer to any information that is not directly linked to your Personal Information and that, standing alone, does not allow for the identification of your individual person.</li>
                <li>"<b>Information</b>" shall refer to "<b>Personal Information</b>" and "<b>Non-Personal Information</b>", collectively.</li>
              </ol>
              <p><b>2. WHAT INFORMATION DO WE COLLECT?</b></p>
              <ol>
                <li><b>Information you provide to us directly.</b> When you register with TalentZoom or otherwise communicate with us, we may collect Personal Information from you such as your first and last name, location, phone number, gender, e-mail and mailing addresses, professional title, company name, employment history, education history, personal summary, and password. We may also collect any communications between you and TalentZoom, communications between you and other users of the Service (including Job Seekers and Employers), and any other information you provide to TalentZoom.</li>
                <li><b>Information collected through the Service.</b> We collect Information about how you use the Service, your actions on the Service, any content that you may upload, post or share with our Service. This includes, without limitation, resumes, job descriptions, text, images, photographs, messages, comments or any other kind of content that you may provide through messages, chats or other functionality on the Site (collectively, “Content”). By using the Service, you consent to the monitoring, recording, storage and disclosure of such communications you send or receive for these purposes. All Content and Information that you decide to make publicly available will be visible to other users of the Service.</li>
                <li><b>Information we receive from third party sites you connect to from our Service.</b> We may also receive Personal Information about you from third parties and combine that with information we collect through our Service. For example, we may obtain information when you login or register with us through a third party social network or authentication service, such as Facebook, LinkedIn, GitHub or Google. These services will authenticate your identity and provide you the option to share certain Personal Information with us, which could include your name, email address, address book and contacts, or other information. Similarly, when you interact with us through a social media site or third party service, such as when you like, follow or share TalentZoom content on any third party social network, we may receive certain Information from the social network including your profile information, picture, user ID associated with your social media account, and any other information you permit the social network to share with third parties. The data we receive from these third party sites is dependent upon that third party’s policies and your privacy settings on that third party site. You should always review, and if necessary, adjust your privacy settings on third-party websites and services before linking or connecting them to our Site or Service.</li>
                <li><b>Location Information.</b> Our servers will also collect your browser type, operating system, Internet Protocol (“IP”), domain name, and/or a date/time stamp for your visit. We may approximate your location by your IP address. We also use the Google Maps API to gather information about your location. Google uses various technologies to determine your location, including IP address, GPs and other sensors that may, for example, provide Google with information on nearby devices, WiFi access points and cell towers (see Google Maps privacy policy to learn more). We maintain location information only so long as you maintain an account with us and then delete location data tied to your personal information. We may maintain de-identified location data for a longer period of time in order to analyze aggregate trends and metrics.</li>
                <li><b>Information we receive from third parties.</b> From time to time, we may receive Information about you from third parties and other users. For example, if a user decides to refer you to our Service, we collect your name and e-mail address from that user in order to follow up with you. We may also collect information about you that is publicly available.</li>
              </ol>
              <p><b>3. HOW DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGY TO COLLECT INFORMATION?</b></p>
              <ol>
                <li><b>Tracking technologies that we use.</b> TalentZoom.io and our third party partners, automatically collect certain types of usage information when you visit our Services, read our emails, or otherwise engage with us in order to maximize the efficiency of your experience on our Site and through our Service. We typically collect this information through a variety of tracking technologies, including, without limitation, cookies, web beacons, embedded scripts, location-identifying technologies, file information and similar technology (collectively, “tracking technologies”). For example, we collect certain Information about your device and its software, such as your IP address, browser type, Internet service provider, platform type, device type, operating system, date and time stamp, a unique ID that allows us to uniquely identify your browser, mobile device or your account, and other such information. We also collect information about the way you use our Service, for example, the site from which you came and the site to which you are going when you leave our Site, the pages you visit, the links you click, how frequently you access the Service, whether you open emails or click the links contained in emails, whether you access the Service from multiple devices, and other actions you take on the Service. When you access our Service from a mobile device, we may collect unique identification numbers associated with your device or our mobile application (including, for example, a UDID, Unique ID for Advertisers (“IDFA”), Google AdID, or Windows Advertising ID), mobile carrier, device type, model and manufacturer, mobile device operating system brand and model, phone number, and depending on your mobile device settings, your geographical location data, including GPS coordinates (e.g., latitude and/or longitude) or similar information regarding the location of your mobile device, or we may be able to approximate a device’s location by analyzing other information, like an IP address. We may collect analytics data, or use third-party analytics tools, to help us measure traffic and usage trends for the Service and to understand more about the demographics of our users. We may also work with third party partners to employ technologies, including the application of statistical modeling tools, which permit us to recognize and contact you across multiple devices. TalentZoom does not monitor, recognize, or honor any opt-out or do not track mechanisms, including general web browser "Do Not Track" settings and/or signals.</li>
                <li><b>How to disable cookies.</b> If you would prefer not to accept cookies, most browsers will allow you to: (a) change your browser settings to notify you when you receive a cookie, which lets you choose whether or not to accept it; (b) disable existing cookies; or (c) set your browser to automatically reject cookies. Please note that doing so may negatively impact your experience using the Service, as some features and services on our Service may not work properly. Depending on your mobile device and operating system, you may not be able to delete or block all cookies. You may also set your e-mail options to prevent the automatic downloading of images that may contain technologies that would allow us to know whether you have accessed our e-mail and performed certain functions with it.</li>
                <li><b>Third party tracking technologies.</b> We and our third party partners may also use cookies and tracking technologies for advertising purposes. For more information about tracking technologies, please see “Third party tracking and online advertising” below.</li>
              </ol>
              <p><b>4. HOW DO WE USE YOUR INFORMATION?</b> We shall use the Information that we collect from you in order to provide you with the service requested and to aid us in serving you best.</p>
              <ol>
                <li><b>Information we collect through tracking technologies.</b> We use or may use the Information collected through tracking technologies to: (a) remember information so that you will not have to re-enter it during your visit or the next time you visit the Site; (b) provide custom, personalized content and information, including targeted content and advertising; (c) recognize and contact you across multiple devices; (d) provide and monitor the effectiveness of our Service; (e) monitor aggregate metrics such as total number of visitors, traffic, usage, and demographic patterns on our Site; (f) diagnose or fix technology problems; and (g) otherwise to plan for and enhance our Service.</li>
                <li><b>Information we collect through other means (as described in Section 2).</b> We use your Information to operate, debug, maintain, and provide to you the features and functionality of the Service, as well as to communicate directly with you, such as to send you email messages and permit you to communicate with other users on the Service, including Job Seekers or Employers, or invite others to join the Service. We may also send you Service-related emails or messages (e.g., account verification, change or updates to features of the Service, technical and security notices) and/or newsletters, surveys, offers or other promotional materials. We may also, upon receiving your consent, publish feedbacks and testimonials that we may receive from you. For more information about your communication preferences, see “Control over your Information” below.</li>
              </ol>
              <p>We may also, upon receiving your consent, publish feedbacks and testimonials that we may receive from you.</p>
              <p><b>5. WHO DO WE SHARE YOUR INFORMATION WITH?</b> We may share your Personal Information in the instances described below. For further information on your choices regarding your information, see the “Control over your Information” section below.</p>
              <p>Remember, our Service allows you to connect and interact with others (including Job Seekers and Employers). If you are a Job Seeker, your profile information, including your name, photo, and other personal information, will be available to Employers.</p>
              <p>We may share your Personal Information with:</p>
              <ol>
                <li>With Employers, if you are a Job Seeker. Your profile information and Content you post to public areas of the Service, will be viewable by Employers on the Service. Please do not provide Personal Information you would not want to be publicly shown to all Employers. For purposes of this Privacy Policy, “public areas” are limited to areas viewable by Employers and not any other users. You may be able to control the visibility of some of your information and actions in your Settings (see "<b>Control over your Information</b>" below);</li>
                <li>Other companies and brands owned or controlled by TalentZoom, and other companies owned by or under common ownership as TalentZoom, which also includes our subsidiaries (i.e., any organization we own or control) or our ultimate holding company (i.e., any organization that owns or controls us) and any subsidiaries it owns. These companies will use your Personal Information in the same way as we can under this Privacy Policy;</li>
                <li>Third-party vendors and other service providers that perform services on our behalf or that we enable integration (e.g., Greenhouse and Lever), as needed to carry out their work for us, which may include identifying and serving targeted advertisements, providing mailing services, providing tax and accounting services, contest fulfillment, web hosting, or providing analytic services;</li>
                <li>The public when you provide feedback or certain Content on our Site. For example, if you post Content on our blog or comment on our social media sites, your information, such as your name, company name, state or province of residence or business, and your comments, may be displayed on our Site or on our social media pages;</li>
                <li>Other parties in connection with a company transaction, such as a merger, sale of company assets or shares, reorganization, financing, change of control or acquisition of all or a portion of our business by another company or third party, or in the event of a bankruptcy or related or similar proceedings; and</li>
                <li>Third parties as required by law or subpoena or if we reasonably believe that such action is necessary to (a) comply with the law and the reasonable requests of law enforcement; (b) to enforce our Terms of Service or to protect the security or integrity of our Service; and/or (c) to exercise or protect the rights, property, or personal safety of TalentZoom, our visitors, or others; <b>We do not sell, trade, or rent your Personal Information to others. We may share generic aggregated demographic information not linked to any Personal Information regarding visitors and users, that does not reasonably identify you directly as an individual, with third parties such as our business partners, trusted affiliates and advertisers for the purposes outlined above.</b></li>
              </ol>
              <p><b>6. CONTROL OVER YOUR INFORMATION.</b></p>
              <ol>
                <li><b>Profile and Data Sharing Settings.</b> You may update your profile information, such as your profile photo, and may change some of your data sharing preferences in your Profile Settings.</li>
                <li><b>How to control your communications preferences:</b> You can stop receiving promotional email communications from us by clicking on the “unsubscribe link” provided in such communications. We make every effort to promptly process all unsubscribe requests. You may not opt out of service-related communications (e.g., account verification, transactional communications, changes/updates to features of the Service, technical and security notices). If you are a Job Seeker, we may also send you text message notifications related to your account and services. For example, we will send a text when an Employer sends you an interview request. By providing a mobile phone number, you authorize TalentZoom to contact you at this number using an automatic texting system to provide information and servicing regarding your account. If you no longer wish to receive SMS texts from us you can unsubscribe by replying “STOP” to one of our texts.</li>
                <li><b>Modifying or deleting your information:</b> If you have any questions about reviewing, modifying, or deleting your Information, you can contact us directly at . support@talentzoom.io. We may not be able to modify or delete your information in all circumstances.</li>
              </ol>
              <p><b>7. THIRD PARTY TRACKING AND ONLINE ADVERTISING.</b> We may share, or we may permit third party online advertising networks, social media companies and other third party services, to collect information about your use of our Site over time so that they may play or display ads on our Service, on other devices you may use, and on other websites, apps or services, including on Facebook. Typically, though not always, the information we share is provided through cookies or similar tracking technologies, which recognize the device you are using and collect information, including click stream information, browser type, time and date you visited the site and other information. We may also share a common account identifier (such as an email address or user ID) to help us identify you across devices. We and our third party partners use this information to make the advertisements you see online more relevant to your interests. As noted above, depending on your browser or mobile device, you may be able set your browser to delete or notify you of cookies and other tracking technology by actively managing the settings on your browser or mobile device. You may also be able to limit interest-based advertising through the settings on your mobile device by selecting “limit ad tracking” (iOS) or “opt-out of interest based ads” (Android). To learn more about interest-based advertising and how you may be able to opt-out of some of this advertising, you may wish to visit the Network Advertising Initiative’s online resources, at <a href="https://www.networkadvertising.org/choices">https://www.networkadvertising.org/choices</a>, and/or the DAA’s resources at <a href="https://www.aboutads.info/choices">https://www.aboutads.info/choices</a>, and you may also adjust your ad preferences through your Facebook settings. Some of these opt-outs may not be effective unless your browser is set to accept cookies. Furthermore, if you use a different device, change browsers or delete the opt-out cookie, you may need to perform the opt-out task again. You may also be able to opt-out of some – but not all – interest-based ads served by mobile ad networks by visiting <a href="https://youradchoices.com/appchoices">https://youradchoices.com/appchoices</a> and downloading the mobile AppChoices app.</p>
              <p><b>8. HOW DO WE STORE AND PROTECT YOUR INFORMATION?</b></p>
              <ol>
                <li><b>Data storage and transfer.</b> Your information collected through our Site may be stored and processed in the United States or any other country in which TalentZoom or its affiliates or service providers maintain facilities. </li>
                <li><b>Keeping your Information safe.</b> We are committed to protecting the security of your Personal Information. Although no security system is impenetrable, we use several industry-standard security technologies and procedures to help protect your Personal Information from unauthorized access, use, or disclosure. No information is 100% secure over the Internet, thus we encourage you to never disclose or share your username and password, and to contact us immediately if you lost them or think that your account has been compromised. In the event that any information under our control is compromised as a result of a breach of security, we will take reasonable steps to investigate the situation and, where appropriate, notify those individuals whose information may have been compromised and take other steps, in accordance with any applicable laws and regulations.</li>
              </ol>
              <p><b>9. LINKS TO OTHER WEBSITES AND SERVICES.</b> Our Site may contain links to third party websites of our business partners, advertisers, and social media sites and our users may post links to third party websites. When you leave our Site and go to another site, please note that these websites have their own privacy policies and that we do not accept any responsibility or liability for their policies. We have no control over, do not review, and cannot be responsible for, these outside websites or their content. Please be aware that the terms of this Privacy Policy do not apply to these outside websites. We strongly recommend that you read their privacy policies and terms and conditions of use to understand how they collect, use, and share information.</p>
              <p><b>10. CHILDREN.</b> We do not knowingly collect or solicit information from anyone under the age of 13 through the Site or Service. In the event that we learn that we have inadvertently collected personal information from a child under age 13, we will delete that information as quickly as possible. If you believe that we might have any information from a child under 13, please contact us at support@talentzoom.io. </p>
              <p><b>11. CHANGES TO THIS PRIVACY POLICY.</b> We may update this Privacy Policy from time to time. When we do, we will notify you and update the “<b>Last Updated</b>” date at the top of this document. Please be aware that continued use of our Site and Service implies your full acknowledgment of the Privacy Policy.</p>
              <p><b>12. HOW TO CONTACT US.</b> If you have any questions about this Privacy Policy, the practices of this Site, or your dealings with this Site, or if you want to report any security issue, please contact us at the following email or address.</p>
              <p>TalentZoom LLC. <br/>Attn: Copyright Agent<br/>________________________________________________<br/>________________________________________________</p>
            </div>
          </div>
        </div>

        <Footer />
      </>
    );
  }
}

export default Privacy;
